export const waterOptions = {
    "Regular": 0,
    "Salty": 10
};

export const rarityOption = {
    "Normal": 0,
    "Rare": 1,
    "Supreme": 2,
    "Fantastic": 3
};

export const skillOptions = {
    'Aggressive fighting': 109,
    'Alchemy': 25,
    'Animal husbandry': 130,
    'Animal taming': 129,
    'Archaeology': 120,
    'Archery': 16,
    'Armour smithing': 22,
    'Axes': 11,
    'Baking': 62,
    'Beverages': 63,
    'Blacksmithing': 59,
    'Blades smithing': 54,
    'Body': 1,
    'Body control': 3,
    'Body stamina': 4,
    'Body strength': 5,
    'Botanizing': 122,
    'Bowyery': 103,
    'Butchering': 77,
    'Butchering knife': 73,
    'Carpentry': 78,
    'Cartography': 135,
    'Carving knife': 72,
    'Catapults': 128,
    'Chain armour smithing': 56,
    'Channeling': 118,
    'Climbing': 123,
    'Cloth tailoring': 52,
    'Clubs': 14,
    'Coal-making': 97,
    'Cooking': 19,
    'Dairy food making': 60,
    'Defensive fighting': 110,
    'Digging': 44,
    'Exorcism': 119,
    'Farming': 33,
    'Fighting': 28,
    'Fine carpentry': 102,
    'Firemaking': 79,
    'First aid': 112,
    'Fishing': 94,
    'Fletching': 104,
    'Foraging': 121,
    'Forestry': 38,
    'Gardening': 36,
    'Halberd': 70,
    'Hammer': 91,
    'Hammers': 15,
    'Hatchet': 50,
    'Healing': 29,
    'Hot food cooking': 61,
    'Huge axe': 88,
    'Huge club': 75,
    'Jewelry smithing': 101,
    'Knives': 12,
    'Large Wooden Shield': 83,
    'Large axe': 87,
    'Large maul': 65,
    'Large metal shield': 85,
    'Leatherworking': 51,
    'Lock picking': 125,
    'Locksmithing': 95,
    'Long bow': 132,
    'Long spear': 69,
    'Longsword': 64,
    'Masonry': 53,
    'Mauls': 13,
    'Meditating': 37,
    'Medium Wooden Shield': 82,
    'Medium bow': 133,
    'Medium maul': 66,
    'Medium metal shield': 86,
    'Metallurgy': 99,
    'Milking': 115,
    'Milling': 98,
    'Mind': 0,
    'Mind logic': 6,
    'Mind speed': 7,
    'Mining': 43,
    'Miscellaneous items': 23,
    'Natural substances': 100,
    'Nature': 26,
    'Normal fighting': 111,
    'Papyrusmaking': 34,
    'Paving': 92,
    'Pickaxe': 45,
    'Plate armour smithing': 57,
    'Polearms': 17,
    'Pottery': 47,
    'Prayer': 117,
    'Preaching': 116,
    'Prospecting': 93,
    'Puppeteering': 106,
    'Rake': 39,
    'Religion': 30,
    'Repairing': 96,
    'Restoration': 137,
    'Ropemaking': 48,
    'Saw': 76,
    'Scythe': 40,
    'Shield bashing': 114,
    'Shield smithing': 58,
    'Shields': 24,
    'Ship building': 134,
    'Short bow': 131,
    'Shortsword': 89,
    'Shovel': 46,
    'Sickle': 41,
    'Small Axe': 42,
    'Small Metal Shield': 84,
    'Small Wooden Shield': 81,
    'Small maul': 67,
    'Smithing': 20,
    'Soul': 2,
    'Soul depth': 8,
    'Soul strength': 9,
    'Staff': 71,
    'Stealing': 126,
    'Stone chisel': 74,
    'Stone cutting': 124,
    'Swords': 10,
    'Tailoring': 18,
    'Taunting': 113,
    'Thatching': 35,
    'Thievery': 31,
    'Toy making': 107,
    'Toys': 27,
    'Tracking': 80,
    'Traps': 127,
    'Trebuchets': 136,
    'Two handed sword': 90,
    'War machines': 32,
    'Warhammer': 68,
    'Weapon heads smithing': 55,
    'Weapon smithing': 21,
    'Weaponless fighting': 108,
    'Woodcutting': 49,
    'Yoyo': 105
};

export const bulkOption = {
    'Barley': 'Barley',
    'Oat': 'Oat',
    'Rye': 'Rye',
    'Wheat': 'Wheat'
}

export const grainAOption = {
    'Barley': 'Barley',
    'Rye': 'Rye',
}

export const grainBOption = {
    'Oat': 'Oat',
    'Wheat': 'Wheat'
}

export const ingredientList = [
    { 'ingredient': 'Cabbage', 'is_vegetable': true, 'weight': 1000 },
    { 'ingredient': 'Carrot', 'is_vegetable': true, 'weight': 500 },
    { 'ingredient': 'Corn', 'is_vegetable': true, 'weight': 100 },
    { 'ingredient': 'Cucumber', 'is_vegetable': true, 'weight': 500 },
    { 'ingredient': 'Garlic', 'is_vegetable': true, 'weight': 50 },
    { 'ingredient': 'Lettuce', 'is_vegetable': true, 'weight': 500 },
    { 'ingredient': 'Onion', 'is_vegetable': true, 'weight': 250 },
    { 'ingredient': 'Pea', 'is_vegetable': true, 'weight': 100 },
    { 'ingredient': 'Pea pod', 'is_vegetable': true, 'weight': 500 },
    { 'ingredient': 'Potato', 'is_vegetable': true, 'weight': 500 },
    { 'ingredient': 'Pumpkin', 'is_vegetable': true, 'weight': 1000 },
    { 'ingredient': 'Tomato', 'is_vegetable': true, 'weight': 500 },
    { 'ingredient': 'Barley', 'is_vegetable': false, 'weight': 300 },
    { 'ingredient': 'Oat', 'is_vegetable': false, 'weight': 300 },
    { 'ingredient': 'Rye', 'is_vegetable': false, 'weight': 300 },
    { 'ingredient': 'Wheat', 'is_vegetable': false, 'weight': 300 },
    { 'ingredient': 'Sugar', 'is_vegetable': false, 'weight': 100 }
]

export const targetingList = [
    { 'fried': 11, 'rye': 4, 'sugar': 2 },
    { 'fried': 12, 'rye': 2, 'sugar': 2 },
    { 'fried': 9, 'rye': 6, 'sugar': 2 },
    { 'fried': 12, 'rye': 1, 'sugar': 2 },
    { 'fried': 9, 'rye': 5, 'sugar': 2 },
    { 'fried': 12, 'rye': 0, 'sugar': 2 },
    { 'fried': 9, 'rye': 4, 'sugar': 2 },
    { 'fried': 8, 'rye': 5, 'sugar': 2 },
    { 'fried': 11, 'rye': 0, 'sugar': 2 },
    { 'fried': 8, 'rye': 4, 'sugar': 2 },
    { 'fried': 7, 'rye': 5, 'sugar': 2 },
    { 'fried': 10, 'rye': 0, 'sugar': 2 },
    { 'fried': 7, 'rye': 4, 'sugar': 2 },
    { 'fried': 6, 'rye': 5, 'sugar': 2 },
    { 'fried': 9, 'rye': 0, 'sugar': 2 },
    { 'fried': 6, 'rye': 4, 'sugar': 2 },
    { 'fried': 5, 'rye': 5, 'sugar': 2 },
    { 'fried': 8, 'rye': 0, 'sugar': 2 },
    { 'fried': 5, 'rye': 4, 'sugar': 2 },
    { 'fried': 4, 'rye': 5, 'sugar': 2 },
    { 'fried': 7, 'rye': 0, 'sugar': 2 },
    { 'fried': 4, 'rye': 4, 'sugar': 2 },
    { 'fried': 3, 'rye': 5, 'sugar': 2 },
    { 'fried': 6, 'rye': 0, 'sugar': 2 },
    { 'fried': 3, 'rye': 4, 'sugar': 2 },
    { 'fried': 2, 'rye': 5, 'sugar': 2 },
    { 'fried': 5, 'rye': 0, 'sugar': 2 },
    { 'fried': 2, 'rye': 4, 'sugar': 2 },
    { 'fried': 1, 'rye': 5, 'sugar': 2 },
    { 'fried': 0, 'rye': 6, 'sugar': 2 },
    { 'fried': 1, 'rye': 4, 'sugar': 2 },
    { 'fried': 0, 'rye': 5, 'sugar': 2 },
    { 'fried': 3, 'rye': 0, 'sugar': 2 },
    { 'fried': 0, 'rye': 4, 'sugar': 2 },
    { 'fried': 1, 'rye': 2, 'sugar': 2 },
    { 'fried': 0, 'rye': 3, 'sugar': 2 },
    { 'fried': 1, 'rye': 1, 'sugar': 2 },
    { 'fried': 12, 'rye': 6, 'sugar': 0 },
    { 'fried': 1, 'rye': 0, 'sugar': 2 },
    { 'fried': 12, 'rye': 5, 'sugar': 0 },
    { 'fried': 11, 'rye': 6, 'sugar': 0 },
    { 'fried': 12, 'rye': 4, 'sugar': 0 },
    { 'fried': 11, 'rye': 5, 'sugar': 0 },
    { 'fried': 12, 'rye': 3, 'sugar': 0 },
    { 'fried': 11, 'rye': 4, 'sugar': 0 },
    { 'fried': 12, 'rye': 2, 'sugar': 0 },
    { 'fried': 9, 'rye': 6, 'sugar': 0 },
    { 'fried': 12, 'rye': 1, 'sugar': 0 },
    { 'fried': 9, 'rye': 5, 'sugar': 0 },
    { 'fried': 12, 'rye': 0, 'sugar': 0 },
    { 'fried': 9, 'rye': 4, 'sugar': 0 },
    { 'fried': 8, 'rye': 5, 'sugar': 0 },
    { 'fried': 11, 'rye': 0, 'sugar': 0 },
    { 'fried': 8, 'rye': 4, 'sugar': 0 },
    { 'fried': 7, 'rye': 5, 'sugar': 0 },
    { 'fried': 10, 'rye': 0, 'sugar': 0 },
    { 'fried': 7, 'rye': 4, 'sugar': 0 },
    { 'fried': 6, 'rye': 5, 'sugar': 0 },
    { 'fried': 9, 'rye': 0, 'sugar': 0 },
    { 'fried': 6, 'rye': 4, 'sugar': 0 },
    { 'fried': 5, 'rye': 5, 'sugar': 0 },
    { 'fried': 8, 'rye': 0, 'sugar': 0 },
    { 'fried': 5, 'rye': 4, 'sugar': 0 },
    { 'fried': 4, 'rye': 5, 'sugar': 0 },
    { 'fried': 7, 'rye': 0, 'sugar': 0 },
    { 'fried': 4, 'rye': 4, 'sugar': 0 },
    { 'fried': 3, 'rye': 5, 'sugar': 0 },
    { 'fried': 6, 'rye': 0, 'sugar': 0 },
    { 'fried': 3, 'rye': 4, 'sugar': 0 },
    { 'fried': 2, 'rye': 5, 'sugar': 0 },
    { 'fried': 5, 'rye': 0, 'sugar': 0 },
    { 'fried': 2, 'rye': 4, 'sugar': 0 },
    { 'fried': 1, 'rye': 5, 'sugar': 0 },
    { 'fried': 0, 'rye': 6, 'sugar': 0 },
    { 'fried': 1, 'rye': 4, 'sugar': 0 },
    { 'fried': 0, 'rye': 5, 'sugar': 0 },
    { 'fried': 3, 'rye': 0, 'sugar': 0 },
    { 'fried': 0, 'rye': 4, 'sugar': 0 },
    { 'fried': 1, 'rye': 2, 'sugar': 0 },
    { 'fried': 0, 'rye': 3, 'sugar': 0 },
    { 'fried': 1, 'rye': 1, 'sugar': 0 },
    { 'fried': 0, 'rye': 2, 'sugar': 0 },
    { 'fried': 1, 'rye': 0, 'sugar': 0 },
    { 'fried': 0, 'rye': 1, 'sugar': 0 },
    { 'fried': 12, 'rye': 6, 'sugar': 1 },
    { 'fried': 0, 'rye': 0, 'sugar': 0 },
    { 'fried': 12, 'rye': 5, 'sugar': 1 },
    { 'fried': 11, 'rye': 6, 'sugar': 1 },
    { 'fried': 12, 'rye': 4, 'sugar': 1 },
    { 'fried': 11, 'rye': 5, 'sugar': 1 },
    { 'fried': 12, 'rye': 3, 'sugar': 1 },
    { 'fried': 11, 'rye': 4, 'sugar': 1 },
    { 'fried': 12, 'rye': 2, 'sugar': 1 },
    { 'fried': 9, 'rye': 6, 'sugar': 1 },
    { 'fried': 12, 'rye': 1, 'sugar': 1 },
    { 'fried': 9, 'rye': 5, 'sugar': 1 },
    { 'fried': 12, 'rye': 0, 'sugar': 1 },
    { 'fried': 9, 'rye': 4, 'sugar': 1 },
    { 'fried': 8, 'rye': 5, 'sugar': 1 },
    { 'fried': 11, 'rye': 0, 'sugar': 1 },
    { 'fried': 8, 'rye': 4, 'sugar': 1 },
    { 'fried': 7, 'rye': 5, 'sugar': 1 },
    { 'fried': 10, 'rye': 0, 'sugar': 1 },
    { 'fried': 7, 'rye': 4, 'sugar': 1 },
    { 'fried': 6, 'rye': 5, 'sugar': 1 },
    { 'fried': 9, 'rye': 0, 'sugar': 1 },
    { 'fried': 6, 'rye': 4, 'sugar': 1 },
    { 'fried': 5, 'rye': 5, 'sugar': 1 },
    { 'fried': 8, 'rye': 0, 'sugar': 1 },
    { 'fried': 5, 'rye': 4, 'sugar': 1 },
    { 'fried': 4, 'rye': 5, 'sugar': 1 },
    { 'fried': 7, 'rye': 0, 'sugar': 1 },
    { 'fried': 4, 'rye': 4, 'sugar': 1 },
    { 'fried': 3, 'rye': 5, 'sugar': 1 },
    { 'fried': 6, 'rye': 0, 'sugar': 1 },
    { 'fried': 3, 'rye': 4, 'sugar': 1 },
    { 'fried': 2, 'rye': 5, 'sugar': 1 },
    { 'fried': 5, 'rye': 0, 'sugar': 1 },
    { 'fried': 2, 'rye': 4, 'sugar': 1 },
    { 'fried': 1, 'rye': 5, 'sugar': 1 },
    { 'fried': 0, 'rye': 6, 'sugar': 1 },
    { 'fried': 1, 'rye': 4, 'sugar': 1 },
    { 'fried': 0, 'rye': 5, 'sugar': 1 },
    { 'fried': 3, 'rye': 0, 'sugar': 1 },
    { 'fried': 0, 'rye': 4, 'sugar': 1 },
    { 'fried': 1, 'rye': 2, 'sugar': 1 },
    { 'fried': 0, 'rye': 3, 'sugar': 1 },
    { 'fried': 1, 'rye': 1, 'sugar': 1 },
    { 'fried': 0, 'rye': 2, 'sugar': 1 },
    { 'fried': 1, 'rye': 0, 'sugar': 1 },
    { 'fried': 0, 'rye': 1, 'sugar': 1 },
    { 'fried': 12, 'rye': 6, 'sugar': 2 },
    { 'fried': 0, 'rye': 0, 'sugar': 1 },
    { 'fried': 12, 'rye': 5, 'sugar': 2 },
    { 'fried': 11, 'rye': 6, 'sugar': 2 },
    { 'fried': 12, 'rye': 4, 'sugar': 2 },
    { 'fried': 11, 'rye': 5, 'sugar': 2 },
    { 'fried': 12, 'rye': 3, 'sugar': 2 }
]